"""
Global configuration for the BTC factor model.

Everything that another module needs to agree on lives here: the forward-return
horizons, the canonical list of parent factor categories, default model
hyper-parameters, and the walk-forward schedule. Keep this file boring and
declarative -- no logic.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from pathlib import Path

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
ROOT = Path(__file__).resolve().parent
ARTIFACTS = ROOT.parent / "artifacts"
ARTIFACTS.mkdir(exist_ok=True)
CACHE = ARTIFACTS / "cache"
CACHE.mkdir(exist_ok=True)

# --------------------------------------------------------------------------- #
# Forward-return horizons (in trading-ish calendar days on a daily grid)
# The model is multi-horizon: one target column per horizon.
# --------------------------------------------------------------------------- #
HORIZONS = {
    "fwd_1d": 1,
    "fwd_5d": 5,
    "fwd_20d": 20,
    "fwd_60d": 60,
    "fwd_6m": 126,   # ~6 trading months
    "fwd_12m": 252,  # ~12 trading months
    "fwd_24m": 504,  # ~2 years -- few independent windows; directional only
}

# --------------------------------------------------------------------------- #
# Parent factor categories. PCA is run *within* each of these blocks so the
# resulting components stay economically interpretable.
# --------------------------------------------------------------------------- #
PARENT_CATEGORIES = [
    "macro_liquidity",
    "funding_stress",     # original: USD/JPY + JPY vol carry-unwind factor
    "risk_appetite",
    "etf_flows",
    "derivatives",        # original: derivative notional / effective float
    "onchain_supply",
    "effective_float",    # original: effective tradable float
    "treasury_demand",    # original: treasury company factor
    "valuation",          # original: power-law deviation
    "momentum",           # price-derived trailing returns + Mayer multiple
    "regulatory",
    "adoption",
]

# --------------------------------------------------------------------------- #
# Normalization / feature config
# --------------------------------------------------------------------------- #
@dataclass
class NormConfig:
    z_window: int = 252           # rolling window for z-scores (1y)
    z_min_periods: int = 60       # require >= this many obs before emitting a z
    winsor_z: float = 5.0         # clip z-scores at +/- this many sigma
    use_robust: bool = True       # median/MAD instead of mean/std


# --------------------------------------------------------------------------- #
# PCA config (applied per parent category)
# --------------------------------------------------------------------------- #
@dataclass
class PCAConfig:
    var_explained: float = 0.90   # keep enough PCs to hit this cumulative var
    max_components: int = 3       # but never more than this per category
    min_features_for_pca: int = 3 # below this, pass features through untouched


# --------------------------------------------------------------------------- #
# Walk-forward validation config
# --------------------------------------------------------------------------- #
@dataclass
class WalkForwardConfig:
    min_train: int = 504          # 2y minimum training window before first test
    test_size: int = 63           # ~quarter-long out-of-sample blocks
    step: int = 63                # advance the origin by one test block each fold
    expanding: bool = True        # expanding (True) vs rolling (False) train window
    # embargo is set per-horizon at runtime = horizon length, to purge the
    # overlap between training targets and the test window (de Prado).


# --------------------------------------------------------------------------- #
# Model hyper-parameters (sane, conservative defaults; tune via the WF harness)
# --------------------------------------------------------------------------- #
@dataclass
class ModelConfig:
    elastic_net_l1_ratios: tuple = (0.1, 0.3, 0.5, 0.7, 0.9, 1.0)
    elastic_net_alphas: int = 20          # alphas auto-generated by CV
    xgb_params: dict = field(default_factory=lambda: {
        "n_estimators": 300,
        "max_depth": 3,                   # shallow: we want robustness, not fit
        "learning_rate": 0.03,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "min_child_weight": 5,
        "reg_lambda": 2.0,
        "objective": "reg:squarederror",
        "n_jobs": 0,
    })
    regime_n_states: int = 2              # e.g. risk-on / risk-off
    regime_feature: str = "risk_appetite" # category whose PC1 drives regimes


@dataclass
class Settings:
    norm: NormConfig = field(default_factory=NormConfig)
    pca: PCAConfig = field(default_factory=PCAConfig)
    wf: WalkForwardConfig = field(default_factory=WalkForwardConfig)
    model: ModelConfig = field(default_factory=ModelConfig)
    random_state: int = 7


SETTINGS = Settings()
